### ISSUE TITLE
GNOME Software displays an age rating of Teen

### ISSUE THREAD

**Issue by tfranken90** [flathub/net.krafting.PleasureDVR#2]
I'm not sure from where GNOME software derives it's age rating, but it currently lists PleasureDVR as suitable for teenagers. If this links to a pornographic site, it should probably be listed as Mature or Adult Only.

**Comment by Krafting** [comment]
This is not an issue with my app sadly, but I guess no such app were uploaded to flathub before, so it went under the radar, I've put the metadata of my application correctly (I suppose), by following the oars specs. (https://hughsie.github.io/oars/generate.html) (https://github.com/hughsie/oars/blob/master/specification/oars-1.1.rnc)

```
  <content_rating type="oars-1.1">
    <content_attribute id="sex-themes">intense</content_attribute>
    <content_attribute id="sex-nudity">intense</content_attribute>
  </content_rating>
```

You should report this to GNOME Software instead.

**Comment by Krafting** [comment]
Also, flathub doesn't seems to show ANY age rating...

**Comment by tfranken90** [comment]
Seems to be an issue with GNOME Software then. I'll report over there and see what they say. thanks!

**Comment by sidt4** [comment]
> Also, flathub doesn't seems to show ANY age rating...

Tracked in https://github.com/flathub-infra/website/issues/114.
